# SPDX-License-Identifier: Apache-2.0
"""Shrunk random-weight pi0 (base) checkpoint (structure test) + its CPU unit tests.

Same intent as ``test_pi0_tiny.py`` (which covers pi0.5 / pi0.52): a real-layout, random-weight,
shrunk checkpoint that proves loading, name mapping, compile and a device forward in minutes.
π0's on-disk layout has no ``model.`` prefix (unlike the LeRobot π0.5 export) and no
``variant_dims`` override exists upstream for π0 — so this generator builds a real
``Pi0ForActionPrediction`` with explicit small Gemma dims via monkeypatched ``get_gemma_config``,
the same technique the real model uses for named variants.

Generate one::

    python test/unit/test_pi0_base_tiny.py --out /path/to/pi0-tiny [--ref /path/to/pi0]
"""

from __future__ import annotations

import argparse
import json
import os

import pytest
import torch

TINY_DIMS = {
    "vision": {
        "hidden_size": 64,
        "intermediate_size": 128,
        "num_hidden_layers": 2,
        "num_attention_heads": 4,
    },
    "paligemma": {
        "width": 64,
        "depth": 2,
        "mlp_dim": 128,
        "num_heads": 8,
        "num_kv_heads": 1,
        "head_dim": 16,
    },
    "action_expert": {
        "width": 32,
        "depth": 2,
        "mlp_dim": 64,
        "num_heads": 8,
        "num_kv_heads": 1,
        "head_dim": 16,
    },
}

_DEFAULT_CONFIG = {
    "type": "pi0",
    "input_features": {
        **{
            f"observation.images.{c}": {"type": "VISUAL", "shape": [3, 224, 224]}
            for c in ("base_0_rgb", "left_wrist_0_rgb", "right_wrist_0_rgb")
        },
        "observation.state": {"type": "STATE", "shape": [32]},
    },
    "output_features": {"action": {"type": "ACTION", "shape": [32]}},
    "paligemma_variant": "gemma_2b",
    "action_expert_variant": "gemma_300m",
    "dtype": "float32",
    "chunk_size": 50,
    "max_state_dim": 32,
    "max_action_dim": 32,
    "num_inference_steps": 10,
    "tokenizer_max_length": 48,
}

# Real lerobot/pi0_base checkpoint dir, for the key-layout test; skipped when unset.
REF_CHECKPOINT = os.environ.get("PI0_WEIGHTS", "")


def make_tiny_checkpoint(
    out_dir: str, ref_dir: str | None = None, seed: int = 0, dims: dict | None = None
) -> str:
    """Write a tiny π0 checkpoint to ``out_dir`` with real structure, random weights."""
    from vllm_omni_neuron.diffusion.models.pi0._vendor.pi0.config import Pi0Config
    from vllm_omni_neuron.diffusion.models.pi0._vendor.pi0.modeling_pi0 import (
        Pi0ForActionPrediction,
    )

    os.makedirs(out_dir, exist_ok=True)
    cfg = dict(_DEFAULT_CONFIG)
    if ref_dir and os.path.exists(os.path.join(ref_dir, "config.json")):
        with open(os.path.join(ref_dir, "config.json")) as f:
            cfg = json.load(f)
    cfg["variant_dims"] = dims or TINY_DIMS
    cfg["device"] = "cpu"
    with open(os.path.join(out_dir, "config.json"), "w") as f:
        json.dump(cfg, f, indent=4)

    torch.manual_seed(seed)
    model = Pi0ForActionPrediction(Pi0Config.from_model_config(cfg))

    with torch.no_grad():
        for name, p in model.named_parameters():
            if p.ndim == 1 and "norm" in name:
                p.normal_(0.0, 0.1)
                if "layer_norm" in name or "post_layernorm" in name:
                    p.add_(1.0 if name.endswith("weight") else 0.0)
            else:
                p.normal_(0.0, 0.02 if p.ndim > 1 else 0.01)
    vt = "paligemma_with_expert.paligemma.model.vision_tower."

    def disk_name(k: str) -> str:  # LeRobot's on-disk SigLIP nesting (transformers <= 5.3)
        if k.startswith(vt) and not k.startswith(vt + "vision_model."):
            k = vt + "vision_model." + k[len(vt) :]
        return k

    state = {
        disk_name(k): v.contiguous().clone()
        for k, v in model.state_dict().items()
        if "rotary_emb" not in k
        and not k.endswith("position_ids")
        and k != "paligemma_with_expert.paligemma.model.language_model.embed_tokens.weight"
    }
    # LeRobot's checkpoint carries gemma_expert's OWN (unused -- gemma_expert.model.embed_tokens is
    # None) lm_head at the ACTION-EXPERT width, not the paligemma embedding width; the model's own
    # randomly-initialized gemma_expert.lm_head.weight already has that shape, so just keep it as-is
    # (it is already in `state` via state_dict() -- no clone-from-elsewhere needed).

    import safetensors.torch

    safetensors.torch.save_file(
        state, os.path.join(out_dir, "model.safetensors"), metadata={"format": "pt"}
    )
    with open(os.path.join(out_dir, "README.md"), "w") as f:
        f.write(
            "Random-weight shrunk pi0 structure-test checkpoint (not a model). "
            "Generated by test/unit/test_pi0_base_tiny.py.\n"
        )
    return out_dir


def _safetensors_keys(path: str) -> dict:
    import struct

    with open(path, "rb") as f:
        n = struct.unpack("<Q", f.read(8))[0]
        header = json.loads(f.read(n))
    header.pop("__metadata__", None)
    return header


# ---------------------------------------------------------------------------------------------
# CPU unit tests
# ---------------------------------------------------------------------------------------------
@pytest.fixture(scope="module")
def tiny_dir(tmp_path_factory):
    ref = REF_CHECKPOINT if os.path.isdir(REF_CHECKPOINT) else None
    return make_tiny_checkpoint(str(tmp_path_factory.mktemp("pi0_tiny")), ref)


def _inputs(cfg, seed=0, n_real_tokens=20, n_real_cams=2):
    g = torch.Generator().manual_seed(seed)
    r = cfg.image_resolution[0]
    images = [torch.rand(1, 3, r, r, generator=g) * 2 - 1 for _ in range(cfg.max_cameras)]
    masks = [torch.tensor([i < n_real_cams]) for i in range(cfg.max_cameras)]
    tokens = torch.zeros(1, cfg.tokenizer_max_length, dtype=torch.long)
    tokens[0, :n_real_tokens] = torch.randint(2, 250000, (n_real_tokens,), generator=g)
    tmask = torch.zeros(1, cfg.tokenizer_max_length, dtype=torch.bool)
    tmask[0, :n_real_tokens] = True
    state = torch.rand(1, cfg.max_state_dim, generator=g) * 2 - 1
    noise = torch.randn(1, cfg.chunk_size, cfg.max_action_dim, generator=g)
    return images, masks, tokens, tmask, state, noise


def test_tiny_key_layout_matches_real(tiny_dir):
    if not os.path.isdir(REF_CHECKPOINT):
        pytest.skip("real pi0 checkpoint not present")
    import re

    tiny = _safetensors_keys(os.path.join(tiny_dir, "model.safetensors"))
    real = _safetensors_keys(os.path.join(REF_CHECKPOINT, "model.safetensors"))

    def keep(k):
        m = re.search(r"\.layers\.(\d+)\.", k)
        return m is None or int(m.group(1)) < 2

    assert set(tiny) == {k for k in real if keep(k)}
    assert all(tiny[k]["dtype"] == real[k]["dtype"] for k in tiny)


def test_tiny_loads_strict(tiny_dir):
    """π0's load_weights warns rather than raises on a mismatch; check completeness via its
    returned filled-params set instead of expecting an exception."""
    import safetensors.torch

    from vllm_omni_neuron.diffusion.models.pi0 import NeuronPi0ActionModel
    from vllm_omni_neuron.diffusion.models.pi0._vendor.pi0.config import Pi0Config

    cfg = Pi0Config.from_pretrained(tiny_dir)
    m = NeuronPi0ActionModel(cfg, dtype=torch.float32)
    state = safetensors.torch.load_file(os.path.join(tiny_dir, "model.safetensors"))
    filled = m.ref.load_weights(state.items())
    params = {
        n
        for n, _ in m.ref.named_parameters()
        if "rotary_emb" not in n and not n.endswith(".inv_freq")
    }
    assert params <= filled, sorted(params - filled)[:10]


@pytest.mark.parametrize("n_real_cams", [3, 1])
def test_graphs_match_upstream_fp32(tiny_dir, n_real_cams):
    """The fixed-shape graphs reproduce the vendored upstream pi0 model exactly in fp32."""
    from vllm_omni_neuron.diffusion.models.pi0 import NeuronPi0ActionModel
    from vllm_omni_neuron.diffusion.models.pi0._vendor.pi0.config import Pi0Config

    cfg = Pi0Config.from_pretrained(tiny_dir)
    m = NeuronPi0ActionModel(cfg, dtype=torch.float32)
    m.load_checkpoint(tiny_dir)
    images, masks, tokens, tmask, state, noise = _inputs(cfg, n_real_cams=n_real_cams)
    with torch.no_grad():
        ref = m.ref.sample_actions(images, masks, tokens, tmask, state, noise=noise.clone())
        out = m.sample_actions(images, masks, tokens, tmask, state, noise=noise.clone())
    rel = ((out - ref).norm() / ref.norm()).item()
    assert out.shape == (1, cfg.chunk_size, cfg.max_action_dim)
    assert rel < 1e-5, rel


def test_graphs_bf16_close(tiny_dir):
    from vllm_omni_neuron.diffusion.models.pi0 import NeuronPi0ActionModel
    from vllm_omni_neuron.diffusion.models.pi0._vendor.pi0.config import Pi0Config

    cfg = Pi0Config.from_pretrained(tiny_dir)
    m32 = NeuronPi0ActionModel(cfg, dtype=torch.float32)
    m32.load_checkpoint(tiny_dir)
    m16 = NeuronPi0ActionModel(cfg, dtype=torch.bfloat16)
    m16.load_checkpoint(tiny_dir)
    images, masks, tokens, tmask, state, noise = _inputs(cfg)
    with torch.no_grad():
        a = m32.sample_actions(images, masks, tokens, tmask, state, noise=noise.clone())
        b = m16.sample_actions(images, masks, tokens, tmask, state, noise=noise.clone())
    rel = ((a - b).norm() / a.norm()).item()
    assert rel < 0.05, rel


def test_prefix_kv_ignores_padding(tiny_dir):
    from vllm_omni_neuron.diffusion.models.pi0 import NeuronPi0ActionModel
    from vllm_omni_neuron.diffusion.models.pi0._vendor.pi0.config import Pi0Config

    cfg = Pi0Config.from_pretrained(tiny_dir)
    m = NeuronPi0ActionModel(cfg, dtype=torch.float32)
    m.load_checkpoint(tiny_dir)
    images, masks, tokens, tmask, state, noise = _inputs(cfg, n_real_cams=2)
    with torch.no_grad():
        a = m.sample_actions(images, masks, tokens, tmask, state, noise=noise.clone())
        tokens2 = tokens.clone()
        tokens2[0, 30:] = 12345
        images2 = list(images)
        images2[2] = torch.zeros_like(images[2])
        b = m.sample_actions(images2, masks, tokens2, tmask, state, noise=noise.clone())
    assert torch.allclose(a, b, atol=1e-6, rtol=0)


def test_pipeline_end_to_end_cpu(tiny_dir):
    """NeuronPi0Pipeline registers, builds from a checkpoint dir and turns a raw robot observation
    into the same action chunk as the vendored upstream model given the same noise."""
    import dataclasses
    import types

    tok_dir = os.path.join(os.environ.get("WEIGHTS", ""), "paligemma-3b-pt-224")
    if not os.path.isdir(tok_dir):
        pytest.skip("PaliGemma tokenizer not present (set WEIGHTS)")

    from vllm_omni.diffusion.data import OmniDiffusionConfig

    import vllm_omni_neuron
    from vllm_omni_neuron.diffusion.models.pi0 import PIPELINE_REGISTRY, NeuronPi0Pipeline
    from vllm_omni_neuron.diffusion.models.pi0._vendor.pi0.processor_pi0 import build_model_inputs

    vllm_omni_neuron._register_pipelines()
    assert {"Pi0Pipeline", "pi0", "Pi05Pipeline", "pi052"} <= {
        e["model_arch"] for e in PIPELINE_REGISTRY
    }

    od = OmniDiffusionConfig.__new__(OmniDiffusionConfig)
    for f in dataclasses.fields(OmniDiffusionConfig):
        setattr(od, f.name, None)
    od.model, od.dtype, od.model_config = tiny_dir, "float32", {}
    od.model_config = {"tokenizer": tok_dir}
    pipe = NeuronPi0Pipeline(od_config=od)

    g = torch.Generator().manual_seed(0)
    cams = [k for k in pipe.config.input_features if "image" in k]
    obs = {
        "prompt": "pick up the red cube",
        **{k: torch.rand(224, 224, 3, generator=g).numpy() for k in cams},
        "state": (torch.rand(pipe.config.max_state_dim, generator=g) * 2 - 1).numpy(),
    }
    noise = torch.randn(1, pipe.config.chunk_size, pipe.config.max_action_dim, generator=g)
    sp = types.SimpleNamespace(
        extra_args={"robot_obs": obs, "noise": noise.clone()}, num_inference_steps=4
    )
    out = pipe.forward(types.SimpleNamespace(sampling_params=sp, prompts=[]))
    assert out.error is None, out.error
    a = torch.from_numpy(out.output["actions"])
    assert a.shape == (pipe.config.chunk_size, pipe.config.max_action_dim)

    im, mk, lt, lm, st = build_model_inputs(obs, pipe.config, pipe.tokenizer, torch.device("cpu"))
    with torch.no_grad():
        ref = pipe.model.ref.sample_actions(im, mk, lt, lm, st, noise=noise.clone(), num_steps=4)[0]
    assert ((a - ref).norm() / ref.norm()).item() < 1e-5


@pytest.mark.parametrize("mode", ["unrolled", "host"])
def test_denoise_modes_match_default(tiny_dir, mode):
    """pi0's per-step device Euler loop (default) == the unrolled graph == the host loop."""
    from vllm_omni_neuron.diffusion.models.pi0 import NeuronPi0ActionModel
    from vllm_omni_neuron.diffusion.models.pi0._vendor.pi0.config import Pi0Config

    cfg = Pi0Config.from_pretrained(tiny_dir)
    m = NeuronPi0ActionModel(cfg, dtype=torch.float32)
    m.load_checkpoint(tiny_dir)
    images, masks, tokens, tmask, state, noise = _inputs(cfg)
    with torch.no_grad():
        a = m.sample_actions(images, masks, tokens, tmask, state, noise=noise.clone(), num_steps=5)
        m.denoise_loop.mode = mode
        b = m.sample_actions(images, masks, tokens, tmask, state, noise=noise.clone(), num_steps=5)
    assert torch.allclose(a, b, atol=1e-6, rtol=0), (a - b).abs().max()


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", required=True)
    ap.add_argument("--ref", default=REF_CHECKPOINT if os.path.isdir(REF_CHECKPOINT) else None)
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args()
    print(make_tiny_checkpoint(a.out, a.ref, a.seed))
